/**
 * Sanitizer and validation utility for extracted price and stock data.
 */

/**
 * Clean and parse price string to a valid positive number.
 * Handles diverse localized formatting generated by the INE mock storefront:
 * - standard Indian format: ₹15,335 or ₹ 15,335.50
 * - unicode fullwidth digits: １５３３５
 * - spaced thousands: ₹15 335
 * - euro format: ₹15.335,00
 * - trailing text: ₹15,335/- (incl. of all taxes)
 * - nbsp/zero-width space interleaved: ₹\u200B1\u00A05\u200B3\u200B3\u200B5
 * - lakh format: Rs. 15,335.00
 * 
 * @param {string|number} rawPrice 
 * @returns {number|null} Valid numeric price or null if invalid
 */
function sanitizePrice(rawPrice) {
  if (rawPrice === null || rawPrice === undefined) {
    return null;
  }

  if (typeof rawPrice === 'number') {
    if (!isFinite(rawPrice) || rawPrice <= 0) return null;
    return Math.round(rawPrice * 100) / 100;
  }

  let str = String(rawPrice).trim();
  if (!str) return null;

  // 1. Normalize unicode (e.g. full-width digits ０-９ to 0-9)
  str = str.normalize('NFKD');

  // 2. Remove zero-width characters and non-breaking spaces
  str = str
    .replace(/[\u200B-\u200D\uFEFF]/g, '')
    .replace(/\u00A0/g, ' ')
    .replace(/\/\-.*$/, '') // trailing "/- (incl. of all taxes)"
    .trim();

  // 3. Remove currency markers
  str = str
    .replace(/[₹$€£]/g, '')
    .replace(/Rs\.?/gi, '')
    .trim();

  // 4. Handle European format e.g. "15.335,00" or "15.335,50"
  if (/\d+\.\d{3},\d{2}$/.test(str) || str.endsWith(',00')) {
    str = str.replace(/\./g, '').replace(/,(\d{2})$/, '.$1');
  }

  // 5. Remove internal spaces between digits (e.g. "15 335" in spaced format)
  str = str.replace(/\s+/g, '');

  // 6. Remove thousands commas (e.g. "15,335.00" -> "15335.00")
  str = str.replace(/,/g, '');

  // 7. Match sign and numeric value
  const match = str.match(/([+-]?\d+(?:\.\d+)?)/);
  if (!match) {
    return null;
  }

  const num = parseFloat(match[1]);
  if (isNaN(num) || !isFinite(num) || num <= 0) {
    return null;
  }

  return Math.round(num * 100) / 100;
}

/**
 * Clean and validate stock status text.
 * 
 * @param {string} rawStock 
 * @returns {string|null} Valid stock status string or null if invalid
 */
function sanitizeStock(rawStock) {
  if (rawStock === null || rawStock === undefined) {
    return null;
  }

  let str = String(rawStock)
    .normalize('NFKD')
    .replace(/[\u200B-\u200D\uFEFF]/g, '')
    .replace(/\u00A0/g, ' ')
    .trim();

  if (!str) return null;

  // Reject placeholder/loading states
  const invalidStates = ['price hidden', 'loading', 'checking availability', 'updating', 'null', 'undefined'];
  if (invalidStates.some(inv => str.toLowerCase().includes(inv))) {
    return null;
  }

  // Normalize common stock messages
  const lower = str.toLowerCase();
  if (lower.includes('out of stock')) {
    return 'Out of Stock';
  }

  const countMatch = str.match(/(\d+)\s*(?:left|in stock)/i) || str.match(/(?:in stock[^\d]*)(\d+)/i);
  if (countMatch) {
    const qty = parseInt(countMatch[1], 10);
    return `In Stock (${qty} units left)`;
  }

  if (lower.includes('in stock')) {
    return 'In Stock';
  }

  return str.slice(0, 100);
}

/**
 * Validate that both price and stock are fully valid.
 * 
 * @param {any} price 
 * @param {any} stock 
 * @returns {{ valid: boolean, error?: string, cleanPrice?: number, cleanStock?: string }}
 */
function validateScrapedData(price, stock) {
  const cleanPrice = sanitizePrice(price);
  if (cleanPrice === null || cleanPrice <= 0) {
    return {
      valid: false,
      error: `Invalid or missing price value: received '${price}'`
    };
  }

  const cleanStock = sanitizeStock(stock);
  if (!cleanStock) {
    return {
      valid: false,
      error: `Invalid or missing stock status: received '${stock}'`
    };
  }

  return {
    valid: true,
    cleanPrice,
    cleanStock
  };
}

module.exports = {
  sanitizePrice,
  sanitizeStock,
  validateScrapedData
};
